# Generated by Django 5.2.4 on 2025-08-05 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camarim', '0002_alter_estoquesala_options_produto_preco_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
