# Generated by Django 5.2.4 on 2025-08-05 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camarim', '0004_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camarim.produto'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.BigIntegerField(),
        ),
    ]
