# Generated by Django 5.2.4 on 2025-08-05 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camarim', '0005_alter_estoque_produto_alter_estoque_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='camarim.produto'),
        ),
    ]
