# Generated by Django 5.2.4 on 2025-08-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camarim', '0006_alter_estoque_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoquesala',
            name='quantidade',
            field=models.BigIntegerField(),
        ),
    ]
