# Generated by Django 5.2.4 on 2025-08-06 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camarim', '0008_remove_proposta_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
