# Generated by Django 5.2.4 on 2025-08-06 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camarim', '0009_proposta_data_criacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposta',
            old_name='data_criacao',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='valor_total',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='valor_total_currency',
        ),
        migrations.AddField(
            model_name='proposta',
            name='impostos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Impostos (%)'),
        ),
        migrations.CreateModel(
            name='ItemProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='camarim.produto')),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='camarim.proposta')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camarim.sala')),
            ],
        ),
        migrations.DeleteModel(
            name='PropostaItem',
        ),
    ]
